x = int(1)   
y = int(2.8) 
z = int("3") 
a = float(1)    
b = float(2.8)  
c = float("3")   
d = float("4.2")
e = str("s1") 
f = str(2)   
i = str(3.0)

print(x, y, z, a, b, c, d, e, f, i)